//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_with_webService.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/alumno_examlple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet alumno_examlple(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/alumno_examlple", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> alumno_examlpleAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Nombre_alumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Nombre_alumno(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Nombre_alumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Nombre_alumnoAsync(int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsForms_with_webService.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsForms_with_webService.ServiceReference1.WebService1Soap>, WindowsForms_with_webService.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet alumno_examlple(int i) {
            return base.Channel.alumno_examlple(i);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> alumno_examlpleAsync(int i) {
            return base.Channel.alumno_examlpleAsync(i);
        }
        
        public string Nombre_alumno(int i) {
            return base.Channel.Nombre_alumno(i);
        }
        
        public System.Threading.Tasks.Task<string> Nombre_alumnoAsync(int i) {
            return base.Channel.Nombre_alumnoAsync(i);
        }
    }
}
